### ISSUE TITLE
error object is not a string

### ISSUE THREAD

**Issue by dannyrz** [vsergeev/lua-periphery#12]
local Serial = require('periphery').Serial
if  Serial==nil then
    print("load sdk periphery  faild.");
    os.exit();
end
local  serial = Serial("/dev/ttyUSB0", 9600)

[Finished in 0.0s with exit code 1]/usr/local/bin/lua: (error object is not a string)

**Comment by vsergeev** [comment]
lua-periphery throws a [table object on an error](https://github.com/vsergeev/lua-periphery#error-handling), which can be formatted into a string with `tostring()`. Unfortunately, Lua 5.1 does not do this automatically (but LuaJIT, Lua 5.2, Lua 5.3 all do).

Try:

``` lua
local serial, err = pcall(Serial, "/dev/ttyUSB0", 9600)
if not serial then
    print(err)
    os.exit()
end
```

Also see issue #4.

I'll add this to the documentation since it's come up a few times now.
